### ISSUE TITLE
maxLength - validation in getError isn't working

### ISSUE THREAD

**Issue by kotmatpockuh** [UltimateAngular/ngxerrors#10]
**Is this a feature request or a bug report?**
Bug

**What's gone wrong?**
I can't check requiredLength of `maxlength` Validator

**What was meant to happen?**
Like with `getError('minlength')?.requiredLength`. With minlength everything is fine.

**Other information**
Check your edited plunker: https://plnkr.co/edit/jhSx3YofWPeLwRRPpTno?p=preview

**Comment by toddmotto** [comment]
Works for me, are you expecting it to show up when `minlength` error is active as well? Screenshot:

 ![screen shot 2017-04-18 at 15 52 28](https://cloud.githubusercontent.com/assets/1655968/25137231/0e06c3e4-244f-11e7-8c0d-fca107dcbb9f.png)

**Comment by kotmatpockuh** [comment]
@toddmotto right, at the same time both: min and max values in same validator

**Comment by toddmotto** [comment]
You'd have to use these independently, because the Object is only available when Angular exposes the error - so in this case `minlength` and `maxlength` are not active errors at the same time. Easiest would be to break them out into two `ngxError` directives if you need the active error Object:

```html
<div ngxErrors="password" #password="ngxErrors">
  <div ngxError="required" when="dirty">
    Password is required
  </div>
  <div ngxError="minlength" when="dirty">
    {{password.getError('minlength')?.requiredLength}} characters minimum
  </div>
  <div ngxError="maxlength" when="dirty">
    {{password.getError('maxlength')?.requiredLength}} characters maximum
  </div>
</div>
```

Sadly we can't get exposed to all errors to cache locally.

**Comment by kotmatpockuh** [comment]
@toddmotto 
sorry for asking here...
is it possible somehow to skip displaying `ngxError="['required']"` when i have `ngxError="['pattern']"`?
