### ISSUE TITLE
Crash in Internet explorer 11

### ISSUE THREAD

**Issue by raiden0610** [UltimateAngular/ngxerrors#12]
**Is this a feature request or a bug report?**
Bug report

**What's gone wrong?**
Internet explorer crash when the app boot

**What was meant to happen?**
Access to the application

**Other information**

![capture](https://cloud.githubusercontent.com/assets/6643835/25202671/75c81156-2556-11e7-8a98-dc4410ed8dcf.JPG)

**Comment by toddmotto** [comment]
Thanks, fixed in 212a010

**Comment by raiden0610** [comment]
Thanks to you too, great library :)
