### ISSUE TITLE
Compatability with IE 9

### ISSUE THREAD

**Issue by EricsG95** [UltimateAngular/ngxerrors#14]
![image](https://cloud.githubusercontent.com/assets/10571842/25331921/4e81e922-2917-11e7-9c1d-1964161f73f8.png)

Unable to run on IE9, despite with polyfils installed, core.js. please let me know which particular ES6 functions are being targeted. Hope that this could be rectify. Thank you so much.

**Comment by toddmotto** [comment]
The error is coming from `polyfills.bundle.js` as per your screenshot, closing this off as there's not any info.

**Comment by EricsG95** [comment]
I understand. Would like to verify does ngxerrors actually support IE9 if polyfills are properly configured? And I am runnning angular cli v.1.0. Thank you!

**Comment by toddmotto** [comment]
Let us know!

**Comment by EricsG95** [comment]
Appreciate your prompt replies.

**Comment by EricsG95** [comment]
The fix for this is to add,
https://www.npmjs.com/package/hidden-attribute-polyfill, in case anyone needed to support IE9.
