### ISSUE TITLE
Group errors in another component

### ISSUE THREAD

**Issue by jogelin** [UltimateAngular/ngxerrors#19]
I would like to centralize errors in one component to avoid repeating : "Field is required",... under each input...

But I was not able to make it works because it is not reconized:
https://plnkr.co/edit/PX2p2QDSGe8CA5h14iLl?p=preview

I tried also to pass directly the FormControl in ngxErrors but I got an error...

**Comment by toddmotto** [comment]
This functionality isn't currently supported, you're doing this: 

```html
<input type="text" formControlName="name">
<error-list [control]="name"></error-list>
```

And your `<error-list>` component has no clue what `"name"` is referring to.

Possibly also related to #11 once this lands.
