### ISSUE TITLE
Display errors when form is submitted

### ISSUE THREAD

**Issue by RodolfoSilva** [UltimateAngular/ngxerrors#2]
# It's a feature.

Sometimes we need display all errors when we submit the form, in AngularJS(1.x) we have an attribute "submitted" in form control, but in Angular(2.x) we do not have. 
Most people use a flag to say this form was submitted, I think we can pass an optional argument saying that the form was submitted, display these errors if it has....

**Comment by markgoho** [comment]
What's the use case for allowing a form to be submitted with errors and then displaying those errors?

**Comment by rynclark** [comment]
I don't think this has a valid use case, personally I think it's quite bad UX to show errors only after a user clicks submit.

I'm going to close this for now, if you do have a use case for it feel free to reply!

**Comment by thigrand** [comment]
A good UX practice is displaying info about status to the user. So when, user fill all fields exept one (required) and click submit. You should display the notification about that to the user.

**Comment by michal-filip** [comment]
What worked well for us in ng1.x was to display errors either when user leaves a specific field (changes its state to touched) OR when he attempts to submit the form. We don't want to display all errors eagerly but at the same time, we want to let the user know, why can't they really submit a form in case they eg. skip some required fields.

**Comment by mtpultz** [comment]
@markgoho @rynclark  I think he means when you have a long form sometimes the user can't find the field that they missed/skipped that is keeping the submit button disabled.  I've seen this cause a lot of confusion in our Angular 1.x and 2.x applications so I don't think blanketing this as bad UX is helpful as it is completely user dependent.  When you allow the submit and force the fields to show validation if they are invalid the user can find them easier based on colour and you get less support requests from clients saying they can't submit a form.

@RodolfoSilva we still allow submission in our applications for the reason I stated above.  I do agree with @markgoho and @rynclark that adding this to the package isn't necessary, but for different reasons.  It's just as easy to apply this to your submit method, which reduces bloat in this package.  This package is more about displaying errors and error related information on a control by control basis, and not handling things related to the forms validity as a whole or submission.  

We do something like this on our projects:

**UtilsService**
```
  public checkFormValidity(form: FormGroup): boolean {
    if (form.invalid) {
      Object.keys(form.controls).forEach(key => {
        const control = form.get(key);
        control.markAsTouched();
        control.markAsDirty();
      });

      return false;
    }

    return true;
  }
```

**Usage**
```
  public onSubmit(): void {
    if (this.utilsService.checkFormValidity(this.form)) {
      const payload = Object.assign({}, this.form.value);

      this.authResource.login(payload)
        .subscribe(
          () => this.onLoginComplete(),
          (error: any) => this.onLoginError(error.message)
        );
    }
  }
```

**Comment by RodolfoSilva** [comment]
@mtpultz Thank for your help, I liked this solution.... And I completely agree @michal-filip

**Comment by michal-filip** [comment]
@mtpultz Thanks for your comment and custom solution sample. After some reading around I also concluded that without FormGroup giving out access to some "submitted" flag there may not be any way for ngxErrors to implement this feature. On the other hand, it's a commonly used UX pattern and it may be worth at least adding an example in readme file.
