### ISSUE TITLE
Optional field but validate if use enter value

### ISSUE THREAD

**Issue by manju-reddys** [UltimateAngular/ngxerrors#20]
**Is this a feature request or a bug report?**
[x] Feature request
**What's gone wrong?**

It's more common in many form's there will be some fields which are optional, if user enter a value the it must be validated

For example: <input type="email">. The email field is optional but must be validate if user enter something in the input to make sure user entered valid email id.

**What was meant to happen?**
Optional field validation

**Other information**

Angular 4.1 and latest ngxerrors.

**Comment by dominique-mueller** [comment]
Isn't this an issue with your validation itself? In the end, ngxErrors only presents the current validation state visually. If you don't set a required() validator, and all other set validators are optional by default (are always valid if the value is empty), your problem should be fixed.

**Comment by toddmotto** [comment]
Closing for now as per above.
