### ISSUE TITLE
Unable to import module in angular-cli 1.0.0

### ISSUE THREAD

**Issue by Greg5ki** [UltimateAngular/ngxerrors#5]
**Is this a feature request or a bug report?**
Bug report

**What's gone wrong?**
Installed npm i @ultimate/ngxerrors.

Imported in app.module.ts. 

Ran ng build --aot and got the following error:

`ERROR in Unexpected value 'NgxErrorsModule in C:/Code/Web.Admin/node_modules/@ultimate/ngxerrors/bundle/ultimate.ngxerrors.umd.js' imported by the module 'AppModule in C:/Code/Web.Admin/src/app/app.module.ts'. Please add a @NgModule annotation`

`ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Code\Web.Admin\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
`

**What was meant to happen?**
Module should import OK

**Other information**
Angular 4.0.2 
angular-cli 1.0.0

**Comment by rynclark** [comment]
Hey, just fixed this in 1.0.0!

**Comment by Greg5ki** [comment]
Awesome!
