### ISSUE TITLE
Feature: Ability to check hasErrors but allow for state[] to be passed similar to hasError's second param

### ISSUE THREAD

**Issue by mtpultz** [UltimateAngular/ngxerrors#6]
**Is this a feature request or a bug report?**
Feature request

The `hasError` method allows us to check for a specific errors elsewhere like 'required' etc, but it would be useful to be able to do something to cover some common cases where you just want to know there are errors and that the input was touched and dirty for UI styling.  I've added methods below with accompanying markup that are examples from Ultimate Angular Pro for encapsulating input state for styling:

```typescript
// Could be solved using #inputError.noErrors(['touched', ...]) since they are not 
// inverse of each other
public formControlSuccess(name: string) {
  return (
    this.parent.get(name).valid &&
    this.parent.get(name).touched
  );
}

// Could be solved using #inputError.hasErrors(['touched', ...])
public formControlDanger(name: string) {
  return (
    !this.parent.get(name).valid &&
    this.parent.get(name).touched
  );
}
```

For markup like this:

```html
<div class="form-group"
      <!-- current -->
      [ngClass]="{
                   'has-success': formControlSuccess('overview.application_date'),
                   'has-danger': formControlDanger('overview.application_date')
                 }">
      <!-- alternative -->
      [ngClass]="{
                   'has-success': #inputError.noErrors(['touched', 'dirty']),
                   'has-danger': #inputError.hasErrors(['touched', 'dirty'])
                 }">

  <label for="application_date"
          class="form-control-label">Application Date</label>

  <input type="text"
          id="application_date"
          class="form-control"
          <!-- current repeated -->
          [ngClass]="{
                       'form-control-success': #inputError.noErrors(['touched', 'dirty']),
                       'form-control-danger': #inputError.hasErrors(['touched', 'dirty'])
                     }"
          placeholder=""
          formControlName="application_date">

  <!--Validation States-->
  <div ngxErrors="overview.application_date"
           #inputError="ngxErrors">
    <small ngxError="required"
            when="touched"
            class="form-control-feedback">
      Required
    </small>
  </div>

  <!--Help-->
  <small class="form-text text-muted">
    Date the borrower applied for the loan.
  </small>

</div>
```

**Comment by toddmotto** [comment]
Hey Martin! I think I may have added this feature earlier? Can you check the docs real quick to see if that's new syntax from today? We did two releases that's all. New api is:

yourError.hasError('required', ['touched', 'dirty']);

If that's not what you're looking for then sorry I misunderstood your comment :D

@toddmotto

**Comment by mtpultz** [comment]
Hi @toddmotto, it is similar, but not specific to a particular error like 'required'.  Instead it would be if there is any error and the field is touched and dirty then lets inform the template similar to the two methods in the PR.

`myError.hasErrors(['touched', 'dirty'])` and if possible the almost, but not quite inverse `myError.noErrors(['touched', 'dirty'])`.  This would mean encapsulate `yourError.hasError('required', ['touched', 'dirty']) || yourError.hasError('email', ['touched', 'dirty']) || ... || N`

**Comment by toddmotto** [comment]
Hey again - was on mobile earlier not my laptop haha. I really misread that email!

I'll get this integrated, likely tomorrow - just need to think of the right method name as `.hasError` prop to method would be a breaking change. I'll get this added for sure.

**Comment by toddmotto** [comment]
Just released this in [1.2.0](https://github.com/UltimateAngular/ngxerrors/releases/tag/1.2.0), syntax:

```html
<div [ngClass]="{
  invalid: myError.hasError('*'),
  invalidTouchedDirty: myError.hasError('*', ['touched', 'dirty'])
}">
</div>
```

Hope that works for you!

**Comment by mtpultz** [comment]
Thanks!!! yah, `hasError` works great.  Only thing I noticed (not that you have to fix it) is if you inverse `hasError` you can't prevent the input success classes from being applied.  Even if you add `touched` or `['touched', 'dirty']`.  That's the only reason I mentioned `noError` since they aren't quite the inverse based on the two methods I provided above, but it does seem to work if I do this:

```
         [ngClass]="{
                      'has-success': !applicantNameError.hasError('*', ['untouched']),
                      'has-danger': applicantNameError.hasError('*', ['touched'])
                    }">
```

The the field is the normal native grey when the template first loads, red if invalid, but if valid and touched it applies `has-success`.

**Comment by mtpultz** [comment]
Actually it makes more sense if you use:

```
         [ngClass]="{
                      'has-success': !applicantNameError.hasError('*', ['invalid', 'untouched']),
                      'has-danger': applicantNameError.hasError('*', ['touched'])
                    }">
```

But unlike this method below when applied all the inputs temporarily light up green:

```
  public formControlSuccess(name: string) {
    return (
      this.parent.get(name).valid &&
      this.parent.get(name).touched
    );
  }
```

**Comment by toddmotto** [comment]
I'll check out if we can add a better fix for this. In the mean time this works:

```html
<[class.no-errors]="!myError.hasError('*') && myError.control.touched">
```

**Comment by toddmotto** [comment]
Optionally we could introduce something like this:

```js
<[class.no-errors]="myError.hasError('!', ['touched'])">
```

Not sure whether introducing this as new `'!'` syntax is a good thing or not, thoughts?

**Comment by mtpultz** [comment]
I got your fix to work by adding an extra check that the control existed.  Using this fix of yours also stops the class being applied temporarily as the template is loaded.

```
'has-success': (!myError.hasError('*') && (myError.control && myError.control.touched)),
```

Using a `!` is consistent with your original solution that uses a recognizable globbing pattern `*` so if documented in usage it doesn't seem out of place, but I do know what you mean.
