### ISSUE TITLE
ngOnDestroy throws error

### ISSUE THREAD

**Issue by Greg5ki** [UltimateAngular/ngxerrors#9]
**Is this a feature request or a bug report?**
More like a feature than a bug

**What's gone wrong?**
UPDATE: Since I posted this issue I found the root cause. Feel free to close.

The issue is that ngxerrors doesn't do a null check on **subscription** in ngOnDestroy function:

`
this.subscription.unsubscribe();
`

**subscription** can be null when one of the names of controls in the template doesn't match any of the names in the related component (developer misspells something).

Have 2 components both of which use ngxerrors. Each component is rendered in a ChildView called tableEditor. When switching between components I call:

```this.tableEditor.clear();```

after that ngxerrors throws an error if the template refers to non-existent controls:

**What was meant to happen?**
No errors thrown. Perhaps a more useful message should be displayed in the console for the developer to check their naming.

**Other information**
ngxerror 1.2.0
angular-cli 1.0.0
Angular 4.0.2

**Comment by toddmotto** [comment]
Thanks for reporting anyway (just read your edit). Ciao for now.
